[tool.coverage.run]
branch = true
source = [ "llm_mocks" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.poetry]
name = "llm-mocks"
version = "0.1.0"
description = "Mock LLMs' responses for unit-tests"
authors = [
  "Vuong Ngo <vuongngo.pd@gmail.com>"
]
repository = "https://github.com/AgiFlow/agiflow-sdks"
documentation = "https://docs.agiflow.io/llm-mocks"
license = "MIT"
readme = "README.md"

[[tool.poetry.packages]]
include = "llm_mocks"

[tool.poetry.dependencies]
python = ">=3.9,<4"
deprecated = "^1.2.14"
wrapt = "^1.16.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.4"
flake8 = "7.0.0"
pytest = "8.1.0"
faker = "^26.0.0"

[tool.poetry.group.test.dependencies]
vcrpy = "^6.0.1"

[project.optional-dependencies]
test = [
  "faker",
]

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
