[tool.coverage.run]
branch = true
source = [ "llm_mocks" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.poetry]
name = "llm-mocks"
version = "0.0.1"
description = "Mock LLMs' responses for unit-tests"
authors = [
  "Vuong Ngo <vuongngo.pd@gmail.com>"
]
repository = "https://github.com/AgiFlow/agiflow-sdks"
documentation = "https://docs.agiflow.io/python_llm_mocks"
license = "MIT"
readme = "README.md"

[[tool.poetry.packages]]
include = "llm_mocks"

[tool.poetry.dependencies]
python = ">=3.9,<4"
pydantic = "^2.5.3"
deprecated = "^1.2.14"
munch = "^4.0.0"
faker = "^25.9.1"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.4"
flake8 = "7.0.0"
pytest = "8.1.0"
pytest-sugar = "1.0.0"
nest-asyncio = "1.6.0"

[tool.poetry.group.test.dependencies]
openai = "^1.30.5"
anthropic = "^0.28.0"
langchain = "^0.2.1"
langchain-community = "^0.2.1"
langchain-openai = "^0.1.8"
vcrpy = "^6.0.1"
pydantic = ">2"
pytest-asyncio = "^0.23.5"
pytest-vcr = "^1.0.2"
pytest-mock = "^3.14.0"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
