export const PLUGIN_CATEGORIES = {
  PII: 1,
  ANSWER_RELEVANCY: 2,
  BIAS: 3,
  TOXICITY: 4,
  CONTEXTUAL_RELEVANCY: 5,
  FAITHFULNESS: 6,
  HALLUCINATION: 7,
} as const;

export const PLUGIN_CATEGORY_NAMES = {
  [PLUGIN_CATEGORIES.PII]: 'PII',
  [PLUGIN_CATEGORIES.ANSWER_RELEVANCY]: 'Answer Relevancy',
  [PLUGIN_CATEGORIES.BIAS]: 'Bias',
  [PLUGIN_CATEGORIES.TOXICITY]: 'Toxicity',
  [PLUGIN_CATEGORIES.CONTEXTUAL_RELEVANCY]: 'Contextual Relevancy',
  [PLUGIN_CATEGORIES.FAITHFULNESS]: 'Faithfulness',
  [PLUGIN_CATEGORIES.HALLUCINATION]: 'Hallucination',
} as const;
