[tool.coverage.run]
branch = true
source = [ "agiflow_eval" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.poetry]
name = "agiflow-eval"
version = "0.0.2"
description = "Agiflow (EVAL) for Python"
authors = [
  "Vuong Ngo <vuongngo.pd@gmail.com>"
]
repository = "https://github.com/AgiFlow/agiflow-sdks"
documentation = "https://docs.agiflow.io/python-agiflow-eval"
license = "MIT"
readme = "README.md"

[[tool.poetry.packages]]
include = "agiflow_eval"

[tool.poetry.dependencies]
python = ">=3.9,<4"
pydantic = "^2.5.3"
deprecated = "^1.2.14"
posthog = "^3.0.2"
litellm = "^1.40.15"
jinja2 = "^3.1.4"
rich = "13.7.1"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.4"
flake8 = "7.0.0"
pytest = "8.1.0"
pytest-sugar = "1.0.0"
nest-asyncio = "1.6.0"
sentry-sdk = "1.43.0"

[tool.poetry.group.test.dependencies]
openai = "^1.30.5"
anthropic = "^0.28.0"
langchain = "^0.2.1"
langchain-community = "^0.2.1"
langchain-openai = "^0.1.8"
vcrpy = "^6.0.1"
pydantic = ">2"
munch = "4.0.0"
pytest-asyncio = "^0.23.5"
pytest-recording = "^0.13.1"
pytest-mock = "^3.14.0"
llm-mocks = "0.1.0"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
