[tool.coverage.run]
branch = true
source = [ "agiflow" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.poetry]
name = "agiflow-sdk"
version = "0.0.24"
description = "Agiflow Software Development Kit (SDK) for Python, support LLM APIs and Frameworks tracing with Opentelemetry and more."
authors = [
  "Vuong Ngo <vuongngo.pd@gmail.com>"
]
repository = "https://github.com/AgiFlow/agiflow-sdks/tree/main/packages/python/agiflow-sdk"
documentation = "https://docs.agiflow.io/python"
license = "MIT"
readme = "README.md"

[[tool.poetry.packages]]
include = "agiflow"

[tool.poetry.dependencies]
python = "<=3.13,>=3.10"
opentelemetry-api = "^1.23.0"
opentelemetry-sdk = "^1.20.0"
opentelemetry-exporter-otlp-proto-http = "^1.20.0"
opentelemetry-instrumentation-requests = "0.44b0"
opentelemetry-instrumentation-sqlalchemy = "0.44b0"
opentelemetry-instrumentation-urllib3 = "0.44b0"
colorama = "^0.4.6"
tenacity = "^8.2.3"
pydantic = "^2.5.3"
deprecated = "^1.2.14"
posthog = "^3.0.2"
tiktoken = "^0.7.0"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.4"
flake8 = "7.0.0"
pytest = "8.1.0"
pytest-sugar = "1.0.0"

[tool.poetry.group.test.dependencies]
openai = "^1.30.5"
anthropic = "^0.28.0"
langchain = "^0.1.9"
langchain-community = "^0.0.38"
langchain-openai = "^0.1.5"
vcrpy = "^6.0.1"
pydantic = ">2"
munch = "4.0.0"
pytest-asyncio = "^0.23.5"
pytest-recording = "^0.13.1"
pytest-mock = "^3.14.0"
cohere = "^5.5.8"
chromadb = "^0.4.9"
pinecone-client = "^4.1.1"
qdrant-client = "^1.9.2"
langgraph = "^0.0.47"
crewai = "^0.35.0"
pymarkdownlnt = "0.9.15"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
